<?php

namespace Database\Seeders;

use App\Models\Cafe;
use Illuminate\Database\Seeder;

class CafeSeeder extends Seeder
{
    /**
     * Seed the cafes table with initial data from CafeFinder.jsx.
     */
    public function run(): void
    {
        $cafes = [
            [
                'name' => 'The Workplace Cafe',
                'vibe_ja' => '#集中 #爆速WiFi',
                'vibe_en' => '#Focus #FastWiFi',
                'desc_ja' => 'セブ最強の作業環境。爆速のWi-Fiと徹底された静寂が学習効率を極限まで高めます。',
                'desc_en' => 'The ultimate study environment with high-speed Wi-Fi.',
                'hours' => '8:00 – 23:00',
                'is_24h' => false,
                'wifi' => 'EXCELLENT',
                'outlet' => 'YES',
                'price' => '₱150〜',
                'price_from' => 150,
                'menu_ja' => 'トリュフクッキー、抹茶ラテ',
                'menu_en' => 'Truffle Cookie, Matcha Latte',
                'seats_ja' => '約50席',
                'seats_en' => 'Approx. 50 seats',
                'noise_ja' => '非常に静か（集中）',
                'noise_en' => 'Very quiet (Focus)',
                'best_ja' => '一人で集中・自習',
                'best_en' => 'Solo focus & study',
                'specs' => [
                    'atmosphere' => '落ち着いた',
                    'bgm' => 'あり（小さめ）',
                    'call' => 'イヤホン推奨',
                    'seats_total' => 50,
                    'seat_types' => ['カウンター', 'テーブル'],
                    'solo_seat' => true,
                    'toilet' => true,
                    'wifi_available' => true,
                    'wifi_limit' => '',
                    'cashless_available' => true,
                    'outlet_detail' => '全席対応',
                ],
                'tips_ja' => '冷房が強力なので上着必須。',
                'tips_en' => 'Strong AC — bring a hoodie.',
                'map_url' => 'https://maps.app.goo.gl/uXv7z9n6hW7yY7v2A',
                'lat' => 10.33080000,
                'lng' => 123.90560000,
                'photos' => ['https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800'],
                'tags' => ['作業向き', 'キャッシュレス'],
                'accent' => '#1B4F8A',
            ],
            [
                'name' => 'Tightrope Coffee',
                'vibe_ja' => '#洗練 #モダン',
                'vibe_en' => '#Modern #Specialty',
                'desc_ja' => '自然光が差し込むミニマルな空間。高品質な一杯と共に優雅な自習時間を。',
                'desc_en' => 'A minimal space with natural light. Perfect for study.',
                'hours' => '7:00 – 22:00',
                'is_24h' => false,
                'wifi' => 'GOOD',
                'outlet' => 'LIMITED',
                'price' => '₱180〜',
                'price_from' => 180,
                'menu_ja' => 'コールドブリュー、アボカドトースト',
                'menu_en' => 'Cold Brew, Avocado Toast',
                'seats_ja' => '約30席',
                'seats_en' => 'Approx. 30 seats',
                'noise_ja' => '静かで上品（小声で）',
                'noise_en' => 'Quiet & elegant (Low voice)',
                'best_ja' => 'PC作業・ノマド',
                'best_en' => 'Laptop work & nomad',
                'specs' => [
                    'atmosphere' => 'おしゃれ',
                    'bgm' => 'あり（小さめ）',
                    'call' => 'イヤホン推奨',
                    'seats_total' => 30,
                    'seat_types' => ['カウンター', 'テーブル', 'テラス'],
                    'solo_seat' => true,
                    'toilet' => true,
                    'wifi_available' => true,
                    'wifi_limit' => '',
                    'cashless_available' => true,
                    'outlet_detail' => '一部席のみ',
                ],
                'tips_ja' => '壁際の席に電源が集中しています。',
                'tips_en' => 'Outlets near wall benches.',
                'map_url' => 'https://maps.google.com',
                'lat' => 10.33230000,
                'lng' => 123.90750000,
                'photos' => ['https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800'],
                'tags' => ['作業向き', '会話OK', 'キャッシュレス'],
                'accent' => '#8B5E3C',
            ],
            [
                'name' => 'Abaca Baking Co.',
                'vibe_ja' => '#朝活 #会話OK',
                'vibe_en' => '#Breakfast #Chic',
                'desc_ja' => '最高のパンと落ち着いた会話。リフレッシュや読書に最適です。',
                'desc_en' => 'Best pastries. Ideal for reading and light work.',
                'hours' => '7:00 – 21:00',
                'is_24h' => false,
                'wifi' => 'AVERAGE',
                'outlet' => 'NO',
                'price' => '₱250〜',
                'price_from' => 250,
                'menu_ja' => 'クロワッサン、カフェラテ',
                'menu_en' => 'Croissant, Cafe Latte',
                'seats_ja' => '約40席',
                'seats_en' => 'Approx. 40 seats',
                'noise_ja' => '適度ににぎやか',
                'noise_en' => 'Moderately lively',
                'best_ja' => 'ミーティング・読書',
                'best_en' => 'Meetings & reading',
                'specs' => [
                    'atmosphere' => 'にぎやか',
                    'bgm' => 'あり（大きめ）',
                    'call' => 'OK',
                    'seats_total' => 40,
                    'seat_types' => ['テーブル', 'テラス'],
                    'solo_seat' => false,
                    'toilet' => true,
                    'wifi_available' => true,
                    'wifi_limit' => '',
                    'cashless_available' => true,
                    'outlet_detail' => 'なし',
                ],
                'tips_ja' => '電源がないためフル充電で。',
                'tips_en' => 'No outlets — come fully charged.',
                'map_url' => 'https://maps.google.com',
                'lat' => 10.32760000,
                'lng' => 123.90680000,
                'photos' => ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
                'tags' => ['会話OK', 'キャッシュレス'],
                'accent' => '#A87550',
            ],
            [
                'name' => "Bo's Coffee",
                'vibe_ja' => '#24時間 #定番',
                'vibe_en' => '#24h #Local',
                'desc_ja' => 'フィリピン産の豆100%。深夜でも安心して利用できます。',
                'desc_en' => 'Reliable 24/7 spot with local beans.',
                'hours' => '0:00 – 24:00',
                'is_24h' => true,
                'wifi' => 'GOOD',
                'outlet' => 'YES',
                'price' => '₱120〜',
                'price_from' => 120,
                'menu_ja' => 'フィリピン産ドリップコーヒー',
                'menu_en' => 'Philippine Origin Drip Coffee',
                'seats_ja' => '約45席',
                'seats_en' => 'Approx. 45 seats',
                'noise_ja' => '適度ににぎやか',
                'noise_en' => 'Moderately lively',
                'best_ja' => '深夜の作業・複数人での勉強',
                'best_en' => 'Late-night study & group work',
                'specs' => [
                    'atmosphere' => 'にぎやか',
                    'bgm' => 'あり（大きめ）',
                    'call' => 'OK',
                    'seats_total' => 45,
                    'seat_types' => ['カウンター', 'テーブル'],
                    'solo_seat' => true,
                    'toilet' => true,
                    'wifi_available' => true,
                    'wifi_limit' => '',
                    'cashless_available' => true,
                    'outlet_detail' => '一部席のみ',
                ],
                'tips_ja' => 'IT Park内に複数あり便利です。',
                'tips_en' => 'Multiple locations in IT Park.',
                'map_url' => 'https://maps.google.com',
                'lat' => 10.32980000,
                'lng' => 123.90620000,
                'photos' => ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800'],
                'tags' => ['24時間', '作業向き', 'キャッシュレス'],
                'accent' => '#2D5016',
            ],
            [
                'name' => 'Civet Coffee',
                'vibe_ja' => '#静か #穴場',
                'vibe_en' => '#Quiet #Hideout',
                'desc_ja' => 'Central Bloc裏の静かな場所。長時間の作業に適しています。',
                'desc_en' => 'A quiet hideout for long stays.',
                'hours' => '8:00 – 0:00',
                'is_24h' => false,
                'wifi' => 'GOOD',
                'outlet' => 'YES',
                'price' => '₱160〜',
                'price_from' => 160,
                'menu_ja' => 'シベットコーヒー、チーズケーキ',
                'menu_en' => 'Civet Coffee, Cheesecake',
                'seats_ja' => '約25席',
                'seats_en' => 'Approx. 25 seats',
                'noise_ja' => '静かで作業向き',
                'noise_en' => 'Quiet & focused',
                'best_ja' => '一人で集中作業',
                'best_en' => 'Focused solo work',
                'specs' => [
                    'atmosphere' => '落ち着いた',
                    'bgm' => 'なし',
                    'call' => 'イヤホン推奨',
                    'seats_total' => 25,
                    'seat_types' => ['カウンター', 'テーブル'],
                    'solo_seat' => true,
                    'toilet' => true,
                    'wifi_available' => true,
                    'wifi_limit' => '',
                    'cashless_available' => true,
                    'outlet_detail' => '全席対応',
                ],
                'tips_ja' => '比較的空いていることが多いです。',
                'tips_en' => 'Usually less crowded.',
                'map_url' => 'https://maps.google.com',
                'lat' => 10.32830000,
                'lng' => 123.90590000,
                'photos' => ['https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800'],
                'tags' => ['作業向き', 'キャッシュレス'],
                'accent' => '#4A7B6F',
            ],
            [
                'name' => 'Tom N Toms Coffee',
                'vibe_ja' => '#広々 #深夜作業',
                'vibe_en' => '#Spacious #24h',
                'desc_ja' => '席数が多く、プレッツェルも美味。24時間集中できます。',
                'desc_en' => 'Spacious and open 24/7. Great pretzels.',
                'hours' => '0:00 – 24:00',
                'is_24h' => true,
                'wifi' => 'GOOD',
                'outlet' => 'YES',
                'price' => '₱170〜',
                'price_from' => 170,
                'menu_ja' => 'プレッツェル、キャラメルマキアート',
                'menu_en' => 'Pretzel, Caramel Macchiato',
                'seats_ja' => '約80席',
                'seats_en' => 'Approx. 80 seats',
                'noise_ja' => '適度ににぎやか',
                'noise_en' => 'Moderately lively',
                'best_ja' => '大人数での勉強・会議',
                'best_en' => 'Group study & meetings',
                'specs' => [
                    'atmosphere' => 'にぎやか',
                    'bgm' => 'あり（大きめ）',
                    'call' => 'OK',
                    'seats_total' => 80,
                    'seat_types' => ['テーブル', 'テラス'],
                    'solo_seat' => true,
                    'toilet' => true,
                    'wifi_available' => true,
                    'wifi_limit' => '',
                    'cashless_available' => true,
                    'outlet_detail' => '一部席のみ',
                ],
                'tips_ja' => '団体でも使いやすい広さです。',
                'tips_en' => 'Good for study groups.',
                'map_url' => 'https://maps.google.com',
                'lat' => 10.32920000,
                'lng' => 123.90540000,
                'photos' => ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800'],
                'tags' => ['24時間', '大人数OK', 'キャッシュレス'],
                'accent' => '#5C4A8A',
            ],
            [
                'name' => 'CBTL',
                'vibe_ja' => '#会話OK #テラス',
                'vibe_en' => '#Terrace #Open',
                'desc_ja' => 'テラス席の雰囲気が最高。夜風を感じながらの学習に。',
                'desc_en' => 'Breezy terrace seating for nighttime study.',
                'hours' => '7:00 – 1:00',
                'is_24h' => false,
                'wifi' => 'AVERAGE',
                'outlet' => 'YES',
                'price' => '₱180〜',
                'price_from' => 180,
                'menu_ja' => 'アイスブレンディッド、ハニーバターブレッド',
                'menu_en' => 'Ice Blended, Honey Butter Bread',
                'seats_ja' => '約60席',
                'seats_en' => 'Approx. 60 seats',
                'noise_ja' => '普通（会話OK）',
                'noise_en' => 'Moderate (Conversation OK)',
                'best_ja' => 'リラックス・気分転換',
                'best_en' => 'Relaxing & refreshing',
                'specs' => [
                    'atmosphere' => 'おしゃれ',
                    'bgm' => 'あり（小さめ）',
                    'call' => 'OK',
                    'seats_total' => 60,
                    'seat_types' => ['テーブル', 'テラス'],
                    'solo_seat' => true,
                    'toilet' => true,
                    'wifi_available' => true,
                    'wifi_limit' => '',
                    'cashless_available' => true,
                    'outlet_detail' => '一部席のみ',
                ],
                'tips_ja' => 'メンバー会員ならWi-Fi無料特典あり。',
                'tips_en' => 'Card members get free Wi-Fi.',
                'map_url' => 'https://maps.google.com',
                'lat' => 10.32950000,
                'lng' => 123.90580000,
                'photos' => ['https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800'],
                'tags' => ['会話OK', 'キャッシュレス'],
                'accent' => '#1B6B8A',
            ],
            [
                'name' => 'Linear Coffee',
                'vibe_ja' => '#本格派 #無機質',
                'vibe_en' => '#Specialty',
                'desc_ja' => 'IT Parkから少し離れた本格派。静寂と香りに浸れます。',
                'desc_en' => 'Best coffee quality in the area. Serious vibe.',
                'hours' => '8:00 – 19:00',
                'is_24h' => false,
                'wifi' => 'AVERAGE',
                'outlet' => 'NO',
                'price' => '₱170〜',
                'price_from' => 170,
                'menu_ja' => 'エスプレッソ、ハンドドリップ',
                'menu_en' => 'Espresso, Hand Drip Coffee',
                'seats_ja' => '約15席',
                'seats_en' => 'Approx. 15 seats',
                'noise_ja' => '非常に静か（会話不可）',
                'noise_en' => 'Very quiet (No conversation)',
                'best_ja' => '本格コーヒーをじっくり味わう',
                'best_en' => 'Savoring specialty coffee',
                'specs' => [
                    'atmosphere' => '落ち着いた',
                    'bgm' => 'なし',
                    'call' => '不可',
                    'seats_total' => 15,
                    'seat_types' => ['カウンター'],
                    'solo_seat' => true,
                    'toilet' => false,
                    'wifi_available' => false,
                    'wifi_limit' => '',
                    'cashless_available' => false,
                    'outlet_detail' => 'なし',
                ],
                'tips_ja' => '静かにコーヒーを味わいたい時に。',
                'tips_en' => 'Perfect for focused coffee moments.',
                'map_url' => 'https://maps.google.com',
                'lat' => 10.32280000,
                'lng' => 123.90220000,
                'photos' => ['https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800'],
                'tags' => ['作業向き'],
                'accent' => '#3A3A3A',
            ],
        ];

        foreach ($cafes as $cafe) {
            Cafe::create($cafe);
        }
    }
}
